NJ-92 Add ticket quantity status
NewtonNetJava/live-only-fanatic pull request #18
Opened 2022-09-10 10:08 UTC by anneliey

2022-09-10 12:35 UTC, Dannebanne94 submitted a review, later dismissed

2022-09-12 07:23 UTC, ManneWas requested changes

2022-09-12 07:23 UTC, ManneWas commented on app/src/components/TicketQuantityStatus.jsx
> +        <svg
import svg instead of copy pasting its code

2022-09-12 08:50 UTC, ManneWas approved these changes

2022-09-12 08:50 UTC, merged