Nj test console
NewtonNetJava/live-only-fanatic pull request #50
Opened 2022-09-20 11:55 UTC by ManneWas

initial carousel stuff, ignore the name i was tired. styling and such will come in a proper landing page PR

2022-09-20 17:03 UTC, Dannebanne94 requested changes

2022-09-20 17:03 UTC, JonssonDani commented on app/src/components/Card.jsx
> +                    <h1 className="title">{data["artist_name"]}</h1>
Vad är anledningen till att vi ändrar till data["artist_name"] men inte på rad 15 till exempel?

2022-09-20 17:03 UTC, JonssonDani commented on app/src/components/CarouselCard.jsx
> +    return <div className={'carousel-card'} id={`slide-${props['key']}-${props['id']}`}>
Om man inspectar i browsern så får man id="slide-undefined-1". Kanske värt att kolla upp?  Verkar inte heller kunna scrolla mellan bilder med knapparna. Pga brist på bilder eller nått som är sönder?

2022-09-20 17:03 UTC, Dannebanne94 commented on app/src/stylesheets/carousel.scss
> +    overflow-scrolling: touch;
Får en lite varning här om att det är en unknown-property,  skulle det vara något annat eller det är med flit?

2022-09-21 13:32 UTC, anneliey approved these changes

2022-09-21 14:00 UTC, JonssonDani approved these changes

2022-09-21 14:01 UTC, merged